version: '3.9'
services:

  news: 
    build: ./news
    ports:
    - "5000:5000" 
    volumes:
    - ./news:/news
    environment:
      - DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend: 
    build: ./frontend 
    ports:
    - "3000:3000"
    volumes:
    - ./frontend:/frontend
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - news

  authentication: 
    build: ./authentication
    ports:
    - "5001:5001" 
    volumes:
    - ./authentication:/authentication
    environment:
      - DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    depends_on:
      - postgres

volumes:
 pgdata: {}